### Do not edit -- Generated by 'configure --with-whatever' from Makefile.in
### RtAudio tests Makefile - for various flavors of unix and MinGW

PROGRAMS = drumbox808
SRC_PATH = .
RM = /bin/rm
INCLUDE = ./inc
OBJECT_PATH = ./obj
LIBDIR = lib
vpath %.o $(OBJECT_PATH)

OBJECTS = RtAudio.o

CC       = g++
DEFS     = -DHAVE_GETTIMEOFDAY -D__LINUX_ALSA__
CFLAGS   = -O2 -Wall -Wextra
CFLAGS  += -I$(INCLUDE)
LIBRARY  = -lpthread -lasound -L$(LIBDIR) -lsoundfile -lncurses

%.o : $(SRC_PATH)/%.cpp
	$(CC) $(CFLAGS) $(DEFS) -c $(<) -o $(OBJECT_PATH)/$@

%.o : ../inc/%.cpp
	$(CC) $(CFLAGS) $(DEFS) -c $(<) -o $(OBJECT_PATH)/$@

all : $(PROGRAMS)

drumbox808 : drumbox808.cpp $(OBJECTS)
	$(CC) $(CFLAGS) $(DEFS) -o drumbox808 drumbox808.cpp $(OBJECT_PATH)/*.o $(LIBRARY)

clean : 
#	$(RM) -f $(OBJECT_PATH)/*.o
	$(RM) -f $(PROGRAMS)
	$(RM) -f *.raw *~ *.exe
	$(RM) -fR *.dSYM

distclean: clean
	$(RM) -f Makefile

strip : 
	strip $(PROGRAMS)

